# Generated by Django 6.0.6 on 2026-06-19 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_app', '0002_emergencyreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyreport',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencyreport',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
