# Generated by Django 6.0.6 on 2026-06-19 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_app', '0004_alter_emergencyreport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyreport',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
